# Site settings
title: "Fatema Tuj Johora Faria"
url: "https://fatemafaria142.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  - publications
  - news

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
